### ISSUE TITLE
Doesn't seem to work (perhaps issue with Fastify?)

### ISSUE THREAD

**Issue by MicroDroid** [abonifacio/nestjs-request-context#5]
I'm not completely sure that Fastify is causing the problem, but basically `req.user` is supposed to be defined, however, the `req` this library provides has the `user` property `undefined`.

**Comment by MicroDroid** [comment]
Maybe the middleware is running *before* the guards?

**Comment by Distortedlogic** [comment]
@MicroDroid yes, middleware runs before guards https://docs.nestjs.com/faq/request-lifecycle

**Comment by abonifacio** [comment]
Closing because it does work with fastify, type improvements will be tackled in #6
