### ISSUE TITLE
Better Typehinting

### ISSUE THREAD

**Issue by Distortedlogic** [abonifacio/nestjs-request-context#6]
This is not a major issue but more a minor convenience thing. The `RequestContextModule` does not utilize generics or allow the dev to pass any a class/interface/type describing the additional props beyond a standard Express Request. I believe in a lot of common use cases, the dev wants to extract the user object they added during auth off the request object.

This has a simple work around by casting `RequestContext.currentContext.req as Request & { user: IUserPassport; }` but this does not feel good or look good and surely there is a better way to allow the dev to say what the default shape of the request object is globally.

Also note the `RequestContextModule` uses express types by default which will force any fastify dev to cast every time regardless any additional props on the request (note I do not use fastify and maybe the types overlap sufficiently for this not to be of any issue).

**Comment by abonifacio** [comment]
Version 2.1.0 is http server agnostic (the same way Nestjs does it) and it can be cast by wrapping the context with a custom class. Examples from test 

https://github.com/abonifacio/nestjs-request-context/blob/eb5f15d2ab8bc2761735938d43e9cdd1a095da57/test/test-context.ts#L3-L11

https://github.com/abonifacio/nestjs-request-context/blob/eb5f15d2ab8bc2761735938d43e9cdd1a095da57/test/test.service.ts#L12-L14
