### ISSUE TITLE
Support nest v10

### ISSUE THREAD

**Issue by mdwekat** [abonifacio/nestjs-request-context#8]
When upgrading to nesJs v10 got an issue

```
npm ERR! Found: @nestjs/common@10.0.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^9.0.5" from nestjs-request-context@2.1.0
npm ERR! node_modules/nestjs-request-context
npm ERR!   nestjs-request-context@"^2.1.0" from the root project
```

**Comment by abonifacio** [comment]
Hey, there's a more elaborated solution now that is actively maintained https://github.com/Papooch/nestjs-cls/issues. I suggest you migrate to that library for faster support and more features

**Comment by GelistirmeKF** [comment]
Would you please adapt to Nestjs v10? We need to make a big change to migrate to nestjs-cls.

Thank you in advance,
KF

**Comment by abonifacio** [comment]
Version 3.0.0 was published

**Comment by GelistirmeKF** [comment]
Thank you so much!
